INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Aguascalientes');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Baja California');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Baja California Sur');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Campeche');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Chiapas');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Chihuahua');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Coahuila');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Colima');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Distrito Federal');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Durango');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Guanajuato');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Guerrero');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Hidalgo');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Jalisco');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Estado de Mexico');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Michoac‡n');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Morelos');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Nayarit');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Nuevo Leon');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Oaxaca');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Puebla');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Queretaro');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Quintana Roo');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'San Luis Potosi');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Sinaloa');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Sonora');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Tabasco');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Tamaulipas');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Tlaxcala');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Veracruz');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Yucat‡n');
INSERT INTO estadosmexico VALUES(nextval('estadoid'), 'Zacatecas');
